config/routes.rb
Rails.application.routes.draw do
  root 'races#home'
  resources :users do
    resources :races, only: [:index, :new, :edit, :destroy]
  end

  resources :races, only: [:create, :update] do
    resources :tweets, only: [:index]
  end

  get '/authenticate' => 'underarmour_data#authenticate'
  get '/callback' => 'underarmour_data#callback'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hash_tag.rb
class HashTag < ApplicationRecord
  belongs_to :race, optional: true
  validates_presence_of :tag
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  belongs_to :race, optional: true
  validates_presence_of :text
end

app/models/race.rb
class Race < ApplicationRecord
  belongs_to :user
  has_many :tweets, dependent: :destroy
  has_many :hash_tags, dependent: :destroy

  validates_presence_of :date, :name, :distance

  accepts_nested_attributes_for :hash_tags, reject_if: lambda { |tag| tag[:tag].blank? }, allow_destroy: true

  module RaceTypes
    MARATHON = {
      name: 'marathon',
      distance: '26.2 miles'
    }
    HALF_MARATHON = {
      name: 'half-marathon',
      distance: '13.1 miles'
    }
    TEN_K = {
      name: '10 K',
      distance: '10 K'
    }
    FIVE_K = {
      name: '5 K',
      distance: '5 K'
    }
    ALL = [MARATHON, HALF_MARATHON, TEN_K, FIVE_K]
  end

  def marathon?
    distance == Distances::MARATHON[:name]
  end

  def half_marathon?
    distance == Distances::HALF_MARATHON[:name]
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :race, optional: true

  validates_presence_of :date, :content
end

app/models/user.rb
class User < ApplicationRecord
  before_validation :downcase_email

  has_many :races, dependent: :destroy
  has_many :workouts, dependent: :destroy
  has_many :tweets, dependent: :destroy

  validates_presence_of :first_name, :last_name, :email
  validates_uniqueness_of :email
  has_secure_password

  def self.authenticate(email, password)
    @user = User.find_by_email(email)
    unless @user.nil?
      return @user if @user.authenticate(password)
    end
    nil
  end

  private

  def downcase_email
    self.email = email.downcase if email.present?
  end
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user
  validates_presence_of :distance, :speed, :pace

  scope :today, -> { where(created_at: DateTime.now.beginning_of_day..DateTime.now.end_of_day) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include RailsUtil::JsonHelper
  include RailsUtil::ReactHelper
  # protect_from_forgery with: :exception

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  before_action :set_hashtag, only: [:update, :destroy]

  def index
    json_with hashtags = Hashtag.all
  end

  def create
    hashtag = Hashtag.new(hashtag_params)
    hashtag.save
    json_with hashtag
  end

  def update
    @hashtag.update_attributes(hashtag_params)
    json_with @hashtag
  end

  def destroy
    @hashtag.destroy
    json_with @hashtag
  end

  private

  def set_hashtag
    @hashtag = Hashtag.find(params[:id])
  end

  def hashtag_params
    @hashtag_params ||= HashtagDecanter.decant(params[:hashtag])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  def home
    render json: { data: Race.first }
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @race = Race.find_by(id: params[:race_id])
    @tweets = @race.tweets
  end
end

app/controllers/underarmour_data_controller.rb
class UnderarmourDataController < ApplicationController
  def authenticate
    @link = UnderArmour::Authentication.new.url
  end

  def callback
    @code = params[:code]
    ua_service.authorize ? redirect_to(root_path) : raise('error retrieving access token')
  end

  def fetch_and_send_data
    # rename / put in rake task
    # get ua activity data with service
    # pass data to twitter service
  end

  private

  def ua_service
    UnderArmour::Authorization.new(code: @code)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_hashtags(race)
    race.hash_tags.map { |tag| '#' + tag.tag }.join(' ')
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RaceTweeter</title>

    <link href="https://fonts.googleapis.com/css?family=Droid+Sans|Lato|Poppins|PT+Sans" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
    <%= csrf_meta_tags %>
  </head>

  <body class="<%= action_name %> <%= controller_name %>">
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= react_component('MainApp') %>

app/views/races/_form.html.erb
<%= simple_form_for @race do |f| %>
  <%= f.error_notification %>
  <%= f.hidden_field :user_id, value: @user.id %>

  <div>
    <%= f.input :name %>
    <%= f.input :date, as: :string %>
    <%= f.input :distance, as: :select, collection: Race::RaceTypes::ALL.map { |type| [type[:name].capitalize, type[:distance]] } %>
  </div>

  <div>
    <%= f.simple_fields_for :hash_tags do |h| %>
      <%= h.input :tag %>
    <% end %>
  </div>

  <div>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/races/edit.html.erb
<header class="header-content">
  <div class="header-holder">
    <h1>Edit Race</h1>
  </div>
</header>

<section class="race-holder">
  <div>
    <%= render 'form', race: @race %>
  </div>
</section>

app/views/races/home.html.erb
<section class="home-container">
  <h1>WELCOME TO RACE TWEETER!</h1>
</section>

app/views/races/index.html.erb
<header class="header-content">
  <div class="header-holder">
    <h1>Your Races</h1>
  </div>
</header>

<p><%= link_to 'New Race', new_user_race_path(user_id: @user.id) %></p>

<section class="race-holder table-holder">
  <table class="">
    <thead>
      <tr>
        <th>Name</th>
        <th>Date</th>
        <th>Distance</th>
        <th>Hashtags</th>
        <th>Tweets</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @races.each do |race| %>
        <tr>
          <td><%= race.name %></td>
          <td><%= race.date.strftime('%-m/%-d/%y') %></td>
          <td><%= race.distance %></td>
          <td><%= display_hashtags(race) %></td>
          <td><%= link_to 'Tweets', race_tweets_path(race_id: race.id) %></td>
          <td><%= link_to 'Edit', edit_user_race_path(user_id: @user.id, id: race.id) %></td>
          <td><%= link_to 'Delete', user_race_path(user_id: @user.id, id: race.id), method: :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/races/new.html.erb
<header class="header-content">
  <div class="header-holder">
    <h1>New Race</h1>
  </div>
</header>

<section class="race-holder">
  <div>
    <%= render 'form', race: @race %>
  </div>
</section>

app/views/tweets/index.html.erb
<h1>Tweets for <%= @race.name %></h1>

<table class="">
  <thead>
    <tr>
      <th>Tweet</th>
      <th>Tweeted At</th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.content %></td>
        <td><%= tweet.created_at.strftime('%l/%M/%p') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/underarmour_data/authenticate.html.erb
<p>Do you want to authorize this application to grab your UnderArmour data?</p>

<a href=<%= "#{@link}" %>><img src="http://developer-ua.mapmyfitness.com.s3.amazonaws.com/assets/login_buttons/UA-login_btn-xlarge.png"></a>